name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-push-docker-images:
    runs-on: ubuntu-22.04

    steps:
      # Checkout your GitHub code
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      # Debugging: List the directory structure to verify paths
      - name: List directory contents
        run: ls -R

      # Login to DockerHub
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push backend image
      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./simple-api # Path to the backend Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      # Build and push database image
      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ./database # Update this if database Dockerfile is located elsewhere
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      # Build and push HTTPd image
      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: ./simple-api # Update this to the correct path for the HTTPd Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest
          push: ${{ github.ref == 'refs/heads/main' }}
